name: Build (Node 14.16.0)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 14.16.0
        uses: actions/setup-node@v4
        with:
          node-version: '14.16.0'
          check-latest: true
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Diagnostics
        run: |
          node -v
          npm -v
          test -f package-lock.json || (echo "package-lock.json is missing; npm ci will fail" && exit 1)

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Build
        run: npm run build
        env:
          CI: "false"   # prevents CRA from failing on warnings
